#!/data/data/com.termux/files/usr/bin/bash
## ~/.bashrc

#### Color Palette Define
	CsReset='\e[0m' CsHighLight='\e[1m' CsUnderLine='\e[4m' CsBlink='\e[5m' CsInvert='\e[7m' CsInvisible='\e[8m' CsNewLine='\n'
	cfBlack='\e[30m' cfdRed='\e[31m' cfdGreen='\e[32m' cfdYellow='\e[33m' cfdBlue='\e[34m' cfdMagenta='\e[35m' cfdCyan='\e[36m' cfdWhite='\e[37m'
	cfGrey='\e[30m\e[1m' cfRed='\e[31m\e[1m' cfGreen='\e[32m\e[1m' cfYellow='\e[33m\e[1m' cfBlue='\e[34m\e[1m' cfMagenta='\e[35m\e[1m' cfCyan='\e[36m\e[1m' cfWhite='\e[37m\e[1m' 
	cbBlack='\e[40m' cbdRed='\e[41m' cbdGreen='\e[42m' cbdYellow='\e[43m' cbdBlue='\e[44m' cbdMagenta='\e[45m' cbdCyan='\e[46m' cbdWhite='\e[47m'
	cbGrey='\e[40m\e[1m' cbRed='\e[41m\e[1m' cbGreen='\e[42m\e[1m' cbYellow='\e[43m\e[1m' cbBlue='\e[44m\e[1m' cbMagenta='\e[45m\e[1m' cbCyan='\e[46m\e[1m' cbWhite='\e[47m\e[1m' 

	PrintRed()(echo -ne "${cfRed}${1}${CsReset}")
	PrintGreen()(echo -ne "${cfGreen}${1}${CsReset}")
	PrintYellow()(echo -ne "${cfYellow}${1}${CsReset}")
	PrintBlue()(echo -ne "${cfBlue}${1}${CsReset}")
	PrintMagenta()(echo -ne "${cfMagenta}${1}${CsReset}")

#	PrintByReturn()
#{
#	if [ "$1" == '0' ]
#	then echo -ne "$cfGreen"
#	else PrintYellow "$1"; echo -ne "$cfRed"
#	fi
#}

#	Prompt()
#{
#	retCode="$?"; echo -ne ' '"${cfCyan}"'\w'' '"$(PrintByReturn "$retCode")"'\$'' '"$CsReset"
#}

PS1=' \e[36m\e[1m\w $(if [ $? == 0 ];then echo -ne \e[32m\e[1m;else echo -ne \e[33m\e[1m"("${?}")"\e[31m\e[1m;fi)\$ \e[0m'

#PS1="$(Prompt)"
PS2='> '
PATH="$PATH"':/data/data/com.termux/files/home/.local/bin'
DISPLAY=':0'

alias l='ls -lAh'

	MountTemp()
{
	[ "$(sudo id -u)" != 0 ] && return 0
	local tempDir uid gid
	tempDir='/data/data/com.termux/files/usr/tmp'
	uid="$(id -u)"
	gid="$(id -g)"
	[ ! -d "$tempDir" ] && mkdir -p "$tempDir"
	sudo mountpoint -q "$tempDir" 2>/dev/null && return 0
	sudo mount -t tmpfs -o mode=700,uid="$uid",gid="$gid" tmpfs "$tempDir"
}

	repeat()
{
	local v; v="$(printf %-"$1"s)";echo "${v// /"$2"}"
}

	todo()
{
	cat << EOF
╔═════╗
║Todo:╟$(repeat "$(( "$COLUMNS" - 7 ))" '─')
╚═════╝
$(cat ~/.termux/todo)
$(repeat "$COLUMNS" '─')
EOF
}


	StartProot()
{
	local rootfs="$1"
	unset LD_PRELOAD
	proot -0 -r "$rootfs" -b /dev -b /proc -b /sys -b "$1"/root:/dev/shm -b /sdcard -b /data/data/com.termux/files/home -w /root /usr/bin/env -i HOME=/root TERM="$TERM" LANG=zh_CN.UTF8 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:~/.local/bin:. "$@"
}

	twl()
{
	termux-wake-lock
}

	nh()
{
	if [ $# = 0 ]; then StartKali; else StartKali -c "$@"; fi
}

	x11()
{
	export DISPLAY=:0
	am start com.termux.x11/com.termux.x11.MainActivity
	termux-x11 &
}

	xfce()
{
	x11 & startxfce4
}

alias mt='cfm'

