#!/data/data/com.termux/files/usr/bin/bash
## ~/.profile

	GetHitokoto()
{
	curl --connect-timeout 0.4 --max-time 0.4 https://v1.hitokoto.cn?encode=text 2>/dev/null && echo || echo '无法连接至一言'
}

	ShowMotd()
{
	if [ $COLUMNS -ge 65 ]
	then cat << EOF
╭────────────────────────────────────────────────────────────────╮
│ ╭──────────────╮                                               │
│ │  __          │ ╭───────╮  github.com/BarryLhm/termux-config  │
│ │  ╲ ╲         │ ╰──╮ ╭──╯                                     │
│ │   ╲ ╲        │    │ │ ╭────╮ ╭─┬──╮╭─┬─────╮ ╭─╮ ╭─╮ ╭────╮  │
│ │   ╱ ╱ ____   │    │ │ │ ── │ │ ╭──╯│ ╭╮ ╭╮ │ │ │ │ │ │ ╲╱ │  │
│ │  ╱_╱ │____│  │    │ │ │ ───┤ │ │   │ ││ ││ │ │ ╰─╯ │ │ ╱╲ │  │
│ │              │    ╰─╯ ╰────╯ ╰─╯   ╰─╯╰─╯╰─╯ ╰───┴─╯ ╰────╯  │
│ ╰──────────────╯  Type "xfce" to start xfce desktop.           │
╰────────────────────────────────────────────────────────────────╯
EOF
	else echo 'Welcome to Termux!'; repeat "$COLUMNS" '─'
	fi
}

#MountTemp
ShowMotd
echo "PID: $$"
GetHitokoto
todo

